---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp XCP文档
    url: "/index.html"
  - title: 发行说明
    url: "/releasenotes.html"
  - title: 开始使用 XCP
    type: solutions
    entries:
    - title: 了解 XCP
      url: "/xcp-index.html"
    - title: XCP NFS 附加功能
      url: "/xcp-nfs-add-ons.html"
    - title: 不支持的功能
      url: "/xcp-unsupported-features.html"
    - title: 支持的配置
      url: "/xcp-supported-configurations.html"
    - title: XCP 使用的端口
      url: "/xcp-ports-used.html"
  - title: 安装 XCP
    entries:
    - title: 准备XCP安装
      url: "/xcp-install-xcp.html"
    - title: 为 XCP NFS 准备 Linux
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: 为 XCP SMB 准备 Windows
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: 准备文件分析
      url: "/xcp-prepare-file-analytics.html"
    - title: 安装 XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: 安装 XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: 安装 NFS 文件分析
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: 安装适用于 SMB 的文件分析
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: 配置 XCP
    entries:
    - title: 配置 XCP NFS 的 ini 文件
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: 性能调整
      url: "/xcp-performance-tuning.html"
    - title: 环境变量
      url: "/xcp-environment-variable.html"
    - title: 配置 POSIX 连接器
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: 配置 HDFS 连接器
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: 配置多节点横向扩展
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: 配置S3连接器
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: 规划数据迁移
    url: "/xcp-plan-data-migration.html"
    entries:
    - title: 规划 NFS 数据迁移
      url: "/xcp-plan-nfs-data-migration.html"
    - title: 规划 SMB 数据迁移
      url: "/xcp-plan-smb-data-migration.html"
    - title: 规划HDFS数据迁移
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: 使用文件分析进行规划
      entries:
      - title: 规划数据迁移
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: 访问文件分析
        url: "/xcp-access-file-analytics.html"
      - title: 添加文件服务器
        url: "/xcp-add-file-servers.html"
      - title: 运行扫描
        url: "/xcp-run-a-scan.html"
    - title: 筛选器
      url: "/xcp-filters.html"
    - title: NFS 和 SMB 的日志记录（可选）
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: 迁移数据
    entries:
    - title: 迁移 NFS 数据
      url: "/xcp-migrate-data.html"
    - title: 迁移 SMB 数据
      url: "/xcp-migrate-smb-data.html"
      entries:
      - title: SMB的NTFS备用数据流迁移
        url: "/xcp-smb-ads.html"
    - title: 迁移HDFS数据
      url: "/xcp-migrate-hdfs-data.html"
    - title: 在同一主机上运行多个XCP作业
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: 其他 NFS 功能
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: 故障排除
    entries:
    - title: 对 XCP NFS 错误进行故障排除
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: 对XCP SMB错误进行故障排除
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: 对 XCP 文件分析错误进行故障排除
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: XCP参考
    entries:
    - title: XCP命令参考概述
      url: "/xcp-reference-overview.html"
    - title: NFS命令参考
      entries:
      - title: 帮助
        url: "/xcp-nfs-reference-help.html"
      - title: 显示
        url: "/xcp-nfs-reference-show.html"
      - title: license
        url: "/xcp-nfs-reference-license.html"
      - title: 激活
        url: "/xcp-nfs-reference-activate.html"
      - title: 扫描
        url: "/xcp-nfs-reference-scan.html"
      - title: 复制
        url: "/xcp-nfs-reference-copy.html"
      - title: 同步
        url: "/xcp-nfs-reference-sync.html"
      - title: 恢复
        url: "/xcp-nfs-reference-resume.html"
      - title: 验证
        url: "/xcp-nfs-reference-verify.html"
      - title: chmod
        url: "/xcp-nfs-reference-chmod.html"
      - title: chown
        url: "/xcp-nfs-reference-chown.html"
      - title: 日志转储
        url: "/xcp-nfs-reference-logdump.html"
      - title: 删除
        url: "/xcp-nfs-reference-delete.html"
      - title: 估计数
        url: "/xcp-nfs-reference-estimate.html"
      - title: 索引删除
        url: "/xcp-nfs-reference-indexdelete.html"
      - title: iSync
        url: "/xcp-nfs-reference-isync.html"
    - title: SMB命令参考
      entries:
      - title: 帮助
        url: "/xcp-smb-reference-help.html"
      - title: 显示
        url: "/xcp-smb-reference-show.html"
      - title: license
        url: "/xcp-smb-reference-license.html"
      - title: 激活
        url: "/xcp-smb-reference-activate.html"
      - title: 扫描
        url: "/xcp-smb-reference-scan.html"
      - title: 复制
        url: "/xcp-smb-reference-copy.html"
      - title: 同步
        url: "/xcp-smb-reference-sync.html"
      - title: 验证
        url: "/xcp-smb-reference-verify.html"
      - title: 配置
        url: "/xcp-smb-reference-configure.html"
      - title: 倾听
        url: "/xcp-smb-reference-listen.html"
    - title: XCP用例
      entries:
      - title: XCP用例
        url: "/xcp-reference-use-cases.html"
    - title: XCP日志记录
      entries:
      - title: 设置logconfig选项
        url: "/xcp-reference-logging-logconfig.html"
      - title: 设置eventlog选项
        url: "/xcp-reference-logging-eventlog.html"
      - title: 启用系统日志客户端
        url: "/xcp-reference-logging-syslog.html"
    - title: XCP事件日志
      entries:
      - title: NFS事件日志
        url: "/xcp-reference-event-logs-nfs.html"
      - title: SMB事件日志
        url: "/xcp-reference-event-logs-smb.html"
  - title: 法律声明
    url: "/legal-notices.html"
