---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: 迁移数据 
---
= 迁移 NFS 数据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用规划迁移之后 `show` 和 `scan` 命令中、您可以迁移NFS数据。



== 复制

`copy` 命令可扫描整个源目录结构并将其复制到目标 NFSv3 导出。`copy` 命令要求源路径和目标路径均为变量。扫描和复制的文件，吞吐量 / 速度以及经过的时间详细信息将在复制操作结束时显示

* 示例： *

[listing]
----
xcp copy <source_nfs_export_path> <destination_nfs_export_path>
----
* POSIX 路径示例： *

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
运行 `xcp help copy` 有关详细信息：



== 恢复

`reume` 命令可通过指定目录索引名称或编号来重新启动先前中断的复制操作。先前复制操作的目录索引名称或编号存储在 ` <catalog path> ： /catalog /index` 目录中。

* 示例： *

[listing]
----
xcp resume -id <catalog_name>
----
运行 `xcp help resume` 有关详细信息：



== 同步

`sync` 命令可使用目录索引标记名称或先前复制操作的编号扫描对源 NFS 目录执行的更改和修改。源增量更改会复制并应用于目标目录。在同步操作 # 之后，旧目录索引编号将替换为新的目录索引编号（ .下划线 ） # 。

* 示例： *

[listing]
----
xcp sync -id <catalog_name>
----
运行 `xcp help sync` 有关详细信息：



== 验证

执行复制操作后， `verify` 命令会对源目录和目标目录进行完整的逐字节数据比较，而不会使用目录索引编号。命令将检查修改时间以及其他文件或目录属性，包括权限。该命令还会读取两端的文件并比较数据。

* 示例： *

[listing]
----
xcp verify <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol
----
* POSIX 路径示例： *

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
运行 `xcp help verify` 有关详细信息：



== iSync

。 `isync` 命令会比较源和目标、并同步目标上的差异、而不使用目录索引。

* 示例 *

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
您可以使用 `isync` 使用 `estimate` 用于估计所需时间的选项 `isync` 命令以同步增量更改。。 `-id` 参数用于指定先前复制操作的目录名称。


NOTE: 如果更改的数据集大小超过已用数据集大小的25%、则 `isync estimate` 命令可能不会显示预期结果。

* 示例 *

[listing]
----
xcp isync estimate -id <name>
----
运行 `xcp help isync` 有关详细信息：
