---
sidebar: sidebar 
permalink: xcp-prepare-linux-for-xcp-nfs.html 
keywords: netapp, xcp, prepare, preparing, preparation, linux, nfs, configure, configuring, catalog, storage, 
summary: 为 XCP NFS 准备 Linux 
---
= 为 XCP NFS 准备 Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS 使用 Linux 客户端主机系统生成并行 I/O 流，并充分利用可用的网络和存储性能。

您可以为 root 用户和非 root 用户配置设置，然后根据您的设置选择任一用户。



== 配置目录

XCP 会将操作报告和元数据保存在可通过 NFSv3 访问的目录目录或具有所需权限的任何 POSIX 路径中。

* 配置目录是一次性的安装前活动。
* 每 1000 万个对象（目录加上文件和硬链接）索引大约 1 GB 的空间；可以恢复或同步的每个副本以及每个脱机可搜索的扫描都需要一个索引。
* 要支持性能，包含导出目录的聚合至少需要十个磁盘或 SSD 。



NOTE: 您必须单独存储 XCP 目录。它们不能位于源 NFS 导出目录或目标 NFS 导出目录中。XCP 会维护元数据，这些元数据是在初始设置期间指定的目录位置中的报告。在使用 XCP 运行任何操作之前，您必须指定并更新用于存储报告的位置。



== 配置存储

XCP NFS 过渡和迁移具有以下源和目标存储要求：

* 源服务器和目标服务器必须启用 NFSv3 或 NFS v4.0 协议服务
+
** 对于 NFSv4 ACL 迁移，必须在目标服务器上启用 NFSv4 协议服务和 NFSv4 ACL 。


* 必须通过 `root` 访问 XCP Linux 客户端主机来导出源卷和目标卷。
* 对于 NFSv4 ACL 迁移， NFSv4 要求对需要迁移 ACL 的卷使用编码语言 UTF-8 。


[NOTE]
====
* 为了防止管理员意外修改源卷，您应将 NFSv3 和 NFSv4 导出目录的源卷配置为只读。
* 在 ONTAP 中，您可以使用诊断 ` -atime-update` 选项来保留 atime 。此功能仅在 ONTAP 中可用，如果您希望在运行 XCP 时在源对象中保留 atime ，则此功能非常有用。


====


== root 用户

Linux 计算机上的 root 用户有权挂载源卷，目标卷和目录卷。



== 非 root 用户

非 root 用户对已挂载的卷具有以下权限：

* 对源卷的读取权限访问
* 对已挂载目标卷的读 / 写权限访问
* 对目录卷的读 / 写权限访问

