---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-smb.html 
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading 
summary: 安装或升级适用于 SMB 的文件分析 
---
= 安装适用于 SMB 的文件分析
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
安装或升级适用于 SMB 的文件分析。

.关于此任务
有关 SMB 的系统要求，请参见 link:xcp-install-xcp-smb.html["安装 XCP SMB"]。

.开始之前
* 要使用 XCP SMB 服务，必须在 Linux 计算机上为 NFS 配置 XCP 文件分析。
* 在 Windows 计算机上开始配置 XCP 文件分析之前，请确保 XCP 服务正在 Linux 计算机上运行。




== 全新安装适用于 SMB 的文件分析

要对 SMB 执行文件分析全新安装，请完成以下步骤。

.步骤
. 复制 `xcp.exe` 文件到Windows `C:` 驱动器、此二进制文件可在内部使用 `/xcp/windows` 在您解压缩后 `tgz` 文件
. 从下载 XCP 许可证文件 link:https://xcp.netapp.com/["XCP 站点"^]。
. 创建文件夹 `C ： \\NetApp\XCP` 并将 XCP 许可证复制到此位置。
. 在命令提示符处使用以下命令激活 XCP 许可证： `xcp.exe activate`
. 在 Windows 命令行界面命令提示符中，运行 `XCP configure` 。
. 出现提示时，提供配置 XCP 文件分析服务器的 Linux 计算机的 IP 地址。
. 复制 `server.key` 和 `server.crt` 文件 `/opt/NetApp/xFiles/xcp/` (在已配置XCP文件分析的Linux框中)为 `C:\NetApp\XCP`。
+
(可选)如果您有CA证书、请将该证书放入 `C:\NetApp\XCP` 具有相同的名称和扩展名。

. 转到Windows计算机并运行 `xcp listen`，现在已配置SMB的XCP文件分析。保持窗口打开以持续运行服务。
. 在支持的浏览器上启动文件分析： `\https://<ip address of linux>/xcp`
+
请参见 link:xcp-install-xcp-smb.html["安装 XCP SMB"] 有关支持的浏览器的信息。

. 选择 ... `OK` 显示对话框时。
+

NOTE: 此时将打开一个新选项卡。如果浏览器上的弹出窗口被阻止、请启用该弹出窗口。

. 接受URL的隐私策略。此时将显示以下消息： `SMB agent is ready to use. Please refresh the analytics page`
. 通过返回到托管XCP文件分析GUI的原始选项卡并刷新页面、在"Agents"卡下显示SMB代理。




== 升级 SMB 文件分析

要升级适用于 SMB 的现有文件分析，请完成以下步骤。

. 在运行文件分析之前、请确认运行文件分析的Linux服务器也已升级、并且该服务正在运行。
. 在 Windows 中，通过在命令行上输入 `CTRL-C` 来停止现有 XCP 服务。
. 替换 `xcp.exe` 使用最新的二进制文件。
. 转到Windows计算机并运行 `xcp listen` 为SMB配置XCP文件分析。保持窗口打开以持续运行服务。
. 在支持的浏览器上启动文件分析： `\https://<ip address of linux>/xcp`
+
请参见 link:xcp-install-xcp-smb.html["安装 XCP SMB"] 有关支持的浏览器的信息。

. 显示对话框时选择*OK*。
+

NOTE: 此时将打开一个新选项卡。如果浏览器上的弹出窗口被阻止、请启用该弹出窗口。

. 接受URL的隐私策略。此时将显示以下消息： `SMB agent is ready to use. Please refresh the analytics page`
. 通过返回到托管XCP文件分析GUI的原始选项卡并刷新页面、在"Agents"卡下显示SMB代理。

